// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOl8O0kokmBlMmLqIUf9B8R6oTMmG-rYM',
    appId: '1:934860007356:web:94bdbed078241bf615adb9',
    messagingSenderId: '934860007356',
    projectId: 'tgscttnkul',
    authDomain: 'tgscttnkul.firebaseapp.com',
    databaseURL: 'https://tgscttnkul-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tgscttnkul.firebasestorage.app',
    measurementId: 'G-W0Z5NFHRLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBi_FAZUEU4uXqmZnm_StF_yTvS4YOpc',
    appId: '1:934860007356:android:f46ee925f201d3b215adb9',
    messagingSenderId: '934860007356',
    projectId: 'tgscttnkul',
    databaseURL: 'https://tgscttnkul-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tgscttnkul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARKiQuiXYCqdVl8nAF6PGbYSseqkIFbYM',
    appId: '1:934860007356:ios:c59c6486cc842b5015adb9',
    messagingSenderId: '934860007356',
    projectId: 'tgscttnkul',
    databaseURL: 'https://tgscttnkul-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tgscttnkul.firebasestorage.app',
    iosBundleId: 'com.example.matkul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARKiQuiXYCqdVl8nAF6PGbYSseqkIFbYM',
    appId: '1:934860007356:ios:c59c6486cc842b5015adb9',
    messagingSenderId: '934860007356',
    projectId: 'tgscttnkul',
    databaseURL: 'https://tgscttnkul-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tgscttnkul.firebasestorage.app',
    iosBundleId: 'com.example.matkul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOl8O0kokmBlMmLqIUf9B8R6oTMmG-rYM',
    appId: '1:934860007356:web:7ff4f8d2d692de9d15adb9',
    messagingSenderId: '934860007356',
    projectId: 'tgscttnkul',
    authDomain: 'tgscttnkul.firebaseapp.com',
    databaseURL: 'https://tgscttnkul-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tgscttnkul.firebasestorage.app',
    measurementId: 'G-ZY33227C7S',
  );
}
